import PropTypes from 'prop-types';

export const propTypes = {
    position: PropTypes.oneOf(['front', 'back']),
    yaxis: PropTypes.arrayOf(PropTypes.shape({
        y: PropTypes.number,
        borderType: PropTypes.oneOf(['solid', 'dotted']),
        borderColor: PropTypes.string,
        offsetX: PropTypes.number,
        offsetY: PropTypes.number,
        yAxisIndex: PropTypes.number,
        label: PropTypes.shape({
            borderColor: PropTypes.string,
            borderWidth: PropTypes.number,
            text: PropTypes.string,
            textAnchor: PropTypes.string,
            position: PropTypes.oneOf(['top', 'bottom']),
            offsetX: PropTypes.number,
            offsetY: PropTypes.number,
            style: PropTypes.shape({
                background: PropTypes.string,
                color: PropTypes.string,
                fontSize: PropTypes.string,
                cssClass: PropTypes.string,
                padding: PropTypes.shape({
                    left: PropTypes.number,
                    right: PropTypes.number,
                    top: PropTypes.number,
                    bottom: PropTypes.number,
                }),
            }),
        }),
    })),
    xaxis: PropTypes.arrayOf(PropTypes.shape({
        x: PropTypes.number,
        borderType: PropTypes.oneOf(['solid', 'dotted']),
        borderColor: PropTypes.string,
        offsetX: PropTypes.number,
        offsetY: PropTypes.number,
        label: PropTypes.shape({
            borderColor: PropTypes.string,
            borderWidth: PropTypes.number,
            text: PropTypes.string,
            textAnchor: PropTypes.string,
            position: PropTypes.oneOf(['top', 'bottom']),
            orientation: PropTypes.oneOf(['vertical', 'horizontal']),
            offsetX: PropTypes.number,
            offsetY: PropTypes.number,
            style: PropTypes.shape({
                background: PropTypes.string,
                color: PropTypes.string,
                fontSize: PropTypes.string,
                cssClass: PropTypes.string,
            }),
        }),
    })),
    point: PropTypes.arrayOf(PropTypes.shape({
        x: PropTypes.oneOfType([
            PropTypes.string,
            PropTypes.number,
        ]),
        y: PropTypes.number,
        yAxisIndex: PropTypes.number,
        seriesIndex: PropTypes.number,
        marker: PropTypes.shape({
            size: PropTypes.number,
            fillColor: PropTypes.string,
            strokeColor: PropTypes.string,
            strokeWidth: PropTypes.number,
            offsetX: PropTypes.number,
            offsetY: PropTypes.number,
            shape: PropTypes.oneOf(['circle', 'square']),
            radius: PropTypes.number,
        }),
        label: PropTypes.shape({
            borderColor: PropTypes.string,
            borderWith: PropTypes.number,
            text: PropTypes.string,
            textAnchor: PropTypes.string,
            offsetX: PropTypes.number,
            offsetY: PropTypes.number,
            style: PropTypes.shape({
                background: PropTypes.string,
                color: PropTypes.string,
                fontSize: PropTypes.string,
                cssClass: PropTypes.string,
                padding: PropTypes.shape({
                    left: PropTypes.number,
                    right: PropTypes.number,
                    top: PropTypes.number,
                    bottom: PropTypes.number,
                }),
            }),
        }),
    })),
};

export const defaultProps = {
    position: 'front',
    yaxis: [
        {
            y: 0,
            borderType: 'solid',
            borderColor: '#B8D3DD',
            offsetX: 0,
            offsetY: -3,
            yAxisIndex: 0,
            label: {
                borderColor: '#c2c2c2',
                borderWidth: 1,
                text: undefined,
                textAnchor: 'end',
                position: 'top',
                offsetX: 0,
                offsetY: 0,
                style: {
                    background: '#fff',
                    color: '#777',
                    fontSize: '12px',
                    cssClass: 'apexcharts-yaxis-annotation-label',
                    padding: {
                        left: 5,
                        right: 5,
                        top: 0,
                        bottom: 2,
                    },
                },
            },
        },
    ],
    xaxis: [
        {
            x: 0,
            borderType: 'solid',
            borderColor: '#B8D3DD',
            offsetX: 0,
            offsetY: 0,
            label: {
                borderColor: '#c2c2c2',
                borderWidth: 1,
                text: undefined,
                textAnchor: 'middle',
                position: 'top',
                orientation: 'vertical',
                offsetX: 0,
                offsetY: 0,
                style: {
                    background: '#fff',
                    color: '#777',
                    fontSize: '12px',
                    cssClass: 'apexcharts-xaxis-annotation-label',
                },
            },
        },
    ],
    point: [
        {
            x: 0,
            y: null,
            yAxisIndex: 0,
            seriesIndex: 0,
            marker: {
                size: 0,
                fillColor: '#fff',
                strokeColor: '#333',
                strokeWidth: 3,
                shape: 'circle',
                radius: 2,
            },
            label: {
                borderColor: '#c2c2c2',
                borderWidth: 1,
                text: undefined,
                textAnchor: 'middle',
                offsetX: 0,
                offsetY: -15,
                style: {
                    background: '#fff',
                    color: '#777',
                    fontSize: '12px',
                    cssClass: 'apexcharts-point-annotation-label',
                    padding: {
                        left: 5,
                        right: 5,
                        top: 0,
                        bottom: 2,
                    },
                },
            },
        },
    ],
};
