import PropTypes from 'prop-types';

export const propTypes = {
    type: PropTypes.oneOf(['categories', 'datetime']),
    categories: PropTypes.arrayOf(PropTypes.oneOfType([
        PropTypes.number,
        PropTypes.string,
    ])),
    labels: PropTypes.shape({
        show: PropTypes.bool,
        rotate: PropTypes.number,
        rotateAlways: PropTypes.bool,
        trim: PropTypes.bool,
        maxHeight: PropTypes.number,
        style: PropTypes.shape({
            color: PropTypes.number,
            fontSize: PropTypes.string,
            cssClass: PropTypes.string,
        }),
        offsetX: PropTypes.number,
        offsetY: PropTypes.number,
        format: PropTypes.string,
        formatter: PropTypes.func,
        dateTimeFormatter: PropTypes.shape({
            year: PropTypes.string,
            month: PropTypes.string,
            day: PropTypes.string,
            hour: PropTypes.string,
        }),
    }),
    axisBorder: PropTypes.shape({
        show: PropTypes.bool,
        color: PropTypes.string,
        offsetX: PropTypes.number,
        offsetY: PropTypes.number,
    }),
    axisTicks: PropTypes.shape({
        show: PropTypes.bool,
        borderType: PropTypes.oneOf(['solid', 'dotted']),
        color: PropTypes.string,
        height: PropTypes.number,
        offsetX: PropTypes.number,
        offsetY: PropTypes.number,
    }),
    tickAmount: PropTypes.number,
    min: PropTypes.number,
    max: PropTypes.number,
    range: PropTypes.number,
    floating: PropTypes.bool,
    position: PropTypes.oneOf(['bottom', 'top']),
    title: PropTypes.shape({
        text: PropTypes.string,
        offsetX: PropTypes.number,
        offsetY: PropTypes.number,
        style: PropTypes.shape({
            color: PropTypes.string,
            fontSize: PropTypes.string,
            cssClass: PropTypes.string,
        }),
    }),
    crosshairs: PropTypes.shape({
        show: PropTypes.bool,
        width: PropTypes.oneOfType([
            PropTypes.number,
            PropTypes.oneOf(['tickWidth', 'barWidth']),
        ]),
        position: PropTypes.oneOf(['back', 'front']),
        opacity: PropTypes.number,
        stroke: PropTypes.shape({
            color: PropTypes.string,
            width: PropTypes.number,
            dashArray: PropTypes.number,
        }),
        fill: PropTypes.shape({
            type: PropTypes.oneOf(['solid', 'gradient']),
            color: PropTypes.string,
            gradient: PropTypes.shape({
                colorFrom: PropTypes.string,
                colorTo: PropTypes.string,
                stops: PropTypes.arrayOf(PropTypes.number),
                opacityFrom: PropTypes.number,
                opacityTo: PropTypes.number,
            }),
        }),
        dropShadow: PropTypes.shape({
            enabled: PropTypes.bool,
            top: PropTypes.number,
            left: PropTypes.number,
            blur: PropTypes.number,
            opacity: PropTypes.number,
        }),
    }),
    tooltip: PropTypes.shape({
        enabled: PropTypes.bool,
        offsetY: PropTypes.number,
    }),
};

export const defaultProps = {
    type: 'categories',
    categories: [],
    labels: {
        show: true,
        rotate: -45,
        rotateAlways: false,
        trim: true,
        maxHeight: 120,
        style: {
            color: undefined,
            fontSize: '12px',
            cssClass: 'apexcharts-xaxis-label',
        },
        offsetX: 0,
        offsetY: 0,
        format: undefined,
        formatter: undefined,
        datetimeFormatter: {
            year: 'yyyy',
            month: "MMM 'yy",
            day: 'dd MMM',
            hour: 'HH:mm',
        },
    },
    axisBorder: {
        show: true,
        color: '#78909C',
        offsetX: 0,
        offsetY: 0,
    },
    axisTicks: {
        show: true,
        borderType: 'solid',
        color: '#78909C',
        height: 6,
        offsetX: 0,
        offsetY: 0,
    },
    tickAmount: undefined,
    min: undefined,
    max: undefined,
    range: undefined,
    floating: false,
    position: 'bottom',
    title: {
        text: undefined,
        offsetX: 0,
        offsetY: 0,
        style: {
            color: undefined,
            fontSize: '12px',
            cssClass: 'apexcharts-xaxis-title',
        },
    },
    crosshairs: {
        show: true,
        width: 1,
        position: 'back',
        opacity: 0.9,
        stroke: {
            color: '#b6b6b6',
            width: 0,
            dashArray: 0,
        },
        fill: {
            type: 'solid',
            color: '#B1B9C4',
            gradient: {
                colorFrom: '#D8E3F0',
                colorTo: '#BED1E6',
                stops: [0, 100],
                opacityFrom: 0.4,
                opacityTo: 0.5,
            },
        },
        dropShadow: {
            enabled: false,
            top: 0,
            left: 0,
            blur: 1,
            opacity: 0.4,
        },
    },
    tooltip: {
        enabled: true,
        offsetY: 0,
    },
};
